name: Build

on:
  push:
    paths-ignore:
     - '**.md'
  pull_request:
    paths-ignore:
     - '**.md'

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest'] # , 'macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Build and test'
        run: mvn verify
        working-directory: colpo.core
